#!/bin/zsh

if (( $# != 1 ))
then
	echo "Usage: cdp search_string"
	exit 1
fi

dirs=$(ls -1 "${PROJDIR}" | gawk "/$1/")

if [[ ! -z "${dirs}" ]]
then
	count=$(echo $dirs | gawk '{print NR}' | tail -1)

	if (( $count == 1 ))
	then
		pushd "${PROJDIR}/${dirs}" >/dev/null
		zsh -l
		popd >/dev/null
	else
		echo "$dirs" | tr ' ' '\n'
	fi
else
	echo "'$1' not found"
	exit 1
fi
