#!/bin/bash

if (( $# > 0 ))
then
	server=$1
	shift
fi

if (( $# > 0 ))
then
	port=$1
else
	port=22
fi

if [[ "${server}" = "" ]]
then
	echo "Please supply a server"
	exit 1
fi

echo "--- Copying profile to ${server}:${port}"
if !(rsync -avPLt -e "ssh -oPort=${port}" ~/.bash_profile ~/.bashrc ~/.complrc ~/.zshenv ~/.zshrc ~/.stingrc ~/.vimrc ~/.colordiffrc ~/.spacemacs ${server}:~/)
then
	echo "Failed to copy profile files"
	exit 1
fi

echo "--- Copying scripts to ${server}:${port}"
if !(rsync -avPLt -e "ssh -oPort=${port}" ~/bin/cb ~/bin/xterm-colors ~/bin/xterm256-colors ${server}:~/bin/)
then
	echo "Failed to copy scripts"
	exit 1
fi

echo "--- Copying vim files to ${server}:${port}"
if !(rsync -avPLt --delete -e "ssh -oPort=${port}" ~/.vim/ ${server}:~/.vim/)
then
	echo "Failed to copy vim files"
	exit 1
fi

echo "--- Copying maven settings file to ${server}:${port}"
if !(rsync -avPLt -e "ssh -oPort=${port}" ~/.m2/settings.xml ${server}:~/.m2/)
then
	echo "Failed to copy maven settings file"
	exit 1
fi

echo "--- Copying good hosts file to ${server}:${port}"
if !(rsync -avPLt -e "ssh -oPort=${port}" ~/.ssh/good_hosts ${server}:~/.ssh/)
then
	echo "Failed to copy good hosts file"
	exit 1
fi
