#!/bin/bash

rcfile=${HOME}/.copystuffrc

if ! [ -f ${rcfile} ]
then
	echo "${rcfile} does not exist!"
	exit 1
fi

gawk '/^[^#]/' ${rcfile} | while read line
do
	array=($line)
	server=${array[0]}
	port=${array[1]}

	if [[ "${server}" = "" ]]
	then
		continue
	fi

	if [[ "${port}" = "" ]]
	then
		port=22
	fi

	if (echo "${server}" | egrep "^#")
	then
		continue
	fi

	if (echo "${port}" | egrep "^#")
	then
		continue
	fi

	copysingle ${server} ${port}
done
